# Generated by Django 2.2.14 on 2020-07-25 03:16

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineComment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('post_id', models.CharField(max_length=24)),
                ('user_id', models.CharField(max_length=24)),
                ('likes', djongo.models.fields.ListField(blank=True, default=[])),
                ('content', models.TextField(max_length=256)),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimelinePost',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('restaurant_id', models.CharField(max_length=24)),
                ('user_id', models.CharField(max_length=24)),
                ('likes', djongo.models.fields.ListField(blank=True, default=[])),
                ('content', models.TextField(max_length=4096)),
                ('Timestamp', models.DateTimeField()),
                ('comments', djongo.models.fields.ListField(blank=True, default=[])),
            ],
        ),
    ]
