version: "3.8"

services:
  client-dev:
    container_name: client-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4200"

  client-prod:
    container_name: client-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "80:80"
