version: "3.8"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
